### ISSUE TITLE
HOW DO I USE THIS ON MY WINDOWS 9

### ISSUE THREAD

**Issue by UE2020** [BlueCannonBall/sockroute#1]
0/10 I DOWNLOADED THE ZIP AND DOUBLE CLICKED THE FILE AND IT DIDNT WORK 😡😡😡😡😡😡😡😡😡😡😠😠😠😠😠😡😡😡😡😠😠😠😠😠😡😡😡😡😠😠😠😠😠😠😡😡😡😡😠😠😠😠😠😡😡😡😡😠😠😠😡😡😡😡😠😠😠😠😠😠😠😡😡😡😡😠😠😠😠😠😠😠😠😠😡😡😡😡😠😠😠😠😠 THIS IS PROBABLY SOME STUPID LINUX CRAP I HATE LINUX 😡😡😡😡😠😠😠😠😠😡😡😡😡😠😠😠😠😠😡😡😡😡😠😠😡😡😡😡😠😠😠😠😠😠😠😡😡😡😡😠😠😠😠😠😠😡😡😡😡😡😡😡😠😠😠😠😠😡😡😡😡😠😠😠😠😠😡😠😠😠😠😠 MAKE IT WORK ON MY WINDOWS 9 STUPID BCB 😡😡😡😡😠😠😠😠😠😡😡😡😡😠😠😠😠😠😡😡😡😡😠😠😠😠😠😡😡😡😡😠😠😠😠😠😡😡😡😡😠😠😠😠😠😡😡😡😡😠😠😠😠😠😡😡😡😡😠😠😠😠😠 LINUXLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMBLINUX IS DUMB IS DUMB

**Comment by Windows8964** [comment]
LMFAO
